spring:
  datasource:
    url: jdbc:mysql://121.36.1.22:3306/xfj-mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: zhangqiang
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
    address: 121.36.1.22:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4


dubbo:
  application:
    name: pay-services
    owner: zq
  protocol:
    name: dubbo
    port: 20831
  registry:
    address: zookeeper://121.36.1.22:2181
    check: true
    group: dubbo-group
    simplified: true
  metadata-report:
    address: zookeeper://121.36.1.22:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-group
  scan:
    base-packages: com.xfj.pay.services
logging:
  config:
    classpath: logback.xml
#支付宝支付相关
ali:
  ali_service: 1111
  ali_partner: 222
  input_charset: 333
  sign_type: 444
  notify_url: 555
  return_url: 666
  seller_id: 777
  seller_email: 888
  pay_gateway_new: 999
  it_b_pay: 1010
  private_key: 12312321
  public_key: 45454
  pay_open_gateway: 2342
  refund_service: 12312
  refund_notify_url: 12312
# 微信支付相关配置
wechat:
  wechat_appid: 123123
  wechat_mch_id: 32423dsfs
  wechat_appsecret: 123dfsf
  wechat_mchsecret: 1231dfd
  wechat_notifyurl: 1231
  wechat_unified_order: 123
  wechat_order_query: 2342
  wechat_refund_url: 2342
  wechat_refund_notify_url: 13

dubbo-group:
  name: test