spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.xfj.shopping.entitys
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
