spring:
  profiles:
    active: test
#mybatis:
#  mapper-locations: classpath*:com/xfj/user/dal/persistence/*Mapper.xml"
#  type-aliases-package: com.xfj.user.entitys

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
