spring:
  profiles:
    active: dev
server:
  port: 6082
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.xfj.comment.entitys
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

