spring:
  datasource:
    url: jdbc:mysql://121.36.1.22:3306/xfj-mall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: zhangqiang
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
    address: 121.36.1.22:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
dubbo:
  application:
    name: comment-service
    owner: Heps
  protocol:
    name: dubbo
    port: 20871
  registry:
    address: zookeeper://121.36.1.22:2181
    check: true
    group: dubbo-group
    simplified: true
  metadata-report:
    address: zookeeper://121.36.1.22:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-group
  scan:
    base-packages: com.xfj.comment.service

dubbo-group:
  name: prod