dubbo:
  application:
    name: xfj-user
    owner: Zq
  registry:
    address: zookeeper://121.36.1.22:2181
    check: true
    group: dubbo-prod
    simplified: true
  metadata-report:
    address: zookeeper://121.36.1.22:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-prod
  scan:
    base-packages: com.xfj.user

captchaFlag : false